name: Workflow of exercise 2
run-name: Workflow2

on:
    push: 
        branches: [main]
    pull_request:
        branches: 
            - main
    workflow_dispatch:
        
    

jobs:
    ubuntu-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello ubuntu"
    macos-job:
        runs-on: macos-latest
        steps:
            - run: |
                echo "Hello mac"
                echo "Hello mac2"
    slow-job:
        runs-on: ubuntu-latest
        steps:
            - name: print
              run: echo "im am slow"
            - name: sleep
              run: sleep 30    
    waiting-job:
        runs-on: ubuntu-latest
        needs: slow-job
        steps:
            - name: ls
              run: ls -l
              
    